
services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_passwd
      POSTGRES_DB: trucks-service-database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
